-- =====================================================================
-- Proyecto Base de Datos 3 - Data Warehouse de vuelos en EE. UU. (2015)
-- DataMart seleccionado: Puntualidad de Vuelos
-- Script 01: esquema, tablas de dimensiones y tabla de hechos
-- DBMS: PostgreSQL 16
--
-- Ejecución:
--   createdb -U postgres -E UTF8 -T template0 dw_vuelos
--   psql -U postgres -d dw_vuelos -f 01_crear_esquema_y_tablas.sql
--
-- ATENCIÓN: el script elimina y vuelve a crear el esquema dw_vuelos.
-- =====================================================================

DROP SCHEMA IF EXISTS dw_vuelos CASCADE;
CREATE SCHEMA dw_vuelos;
COMMENT ON SCHEMA dw_vuelos IS 'DataMart Puntualidad de Vuelos - vuelos comerciales de EE. UU. (2015)';

SET search_path TO dw_vuelos;

-- ---------------------------------------------------------------------
-- DIMENSIÓN FECHA
-- Clave inteligente AAAAMMDD; se genera completa antes del ETL.
-- Jerarquía: Año > Trimestre > Mes > Fecha (y Día de la semana)
-- ---------------------------------------------------------------------
CREATE TABLE dim_fecha (
    sk_fecha          INTEGER      NOT NULL,
    fecha             DATE         NOT NULL,
    dia               SMALLINT     NOT NULL,
    dia_semana        SMALLINT     NOT NULL,
    nombre_dia        VARCHAR(10)  NOT NULL,
    es_fin_de_semana  BOOLEAN      NOT NULL,
    mes               SMALLINT     NOT NULL,
    nombre_mes        VARCHAR(10)  NOT NULL,
    trimestre         SMALLINT     NOT NULL,
    anio              SMALLINT     NOT NULL,
    CONSTRAINT pk_dim_fecha PRIMARY KEY (sk_fecha),
    CONSTRAINT uq_dim_fecha_fecha UNIQUE (fecha),
    CONSTRAINT ck_dim_fecha_sk CHECK (sk_fecha = EXTRACT(YEAR FROM fecha) * 10000
                                               + EXTRACT(MONTH FROM fecha) * 100
                                               + EXTRACT(DAY FROM fecha)),
    CONSTRAINT ck_dim_fecha_dia CHECK (dia BETWEEN 1 AND 31),
    CONSTRAINT ck_dim_fecha_dia_semana CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT ck_dim_fecha_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_fecha_trimestre CHECK (trimestre BETWEEN 1 AND 4)
);

COMMENT ON TABLE  dim_fecha IS 'Dimensión calendario: un registro por día';
COMMENT ON COLUMN dim_fecha.sk_fecha   IS 'Clave sustituta inteligente con formato AAAAMMDD';
COMMENT ON COLUMN dim_fecha.dia_semana IS '1 = lunes ... 7 = domingo (igual que DAY_OF_WEEK del dataset)';

-- ---------------------------------------------------------------------
-- DIMENSIÓN HORA (hora programada de salida)
-- Jerarquía: Franja horaria > Hora
-- ---------------------------------------------------------------------
CREATE TABLE dim_hora (
    sk_hora         SMALLINT     NOT NULL,
    hora_texto      CHAR(5)      NOT NULL,
    franja_horaria  VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_dim_hora PRIMARY KEY (sk_hora),
    CONSTRAINT ck_dim_hora CHECK (sk_hora BETWEEN 0 AND 23),
    CONSTRAINT ck_dim_hora_franja CHECK (franja_horaria IN ('Madrugada', 'Mañana', 'Tarde', 'Noche'))
);

COMMENT ON TABLE  dim_hora IS 'Hora del día (0-23) de la salida programada, agrupada en franjas';
COMMENT ON COLUMN dim_hora.sk_hora IS 'Hora entera: SCHEDULED_DEPARTURE (hhmm) / 100';

-- ---------------------------------------------------------------------
-- DIMENSIÓN AEROLÍNEA
-- Fuente: airlines.csv
-- ---------------------------------------------------------------------
CREATE TABLE dim_aerolinea (
    sk_aerolinea      INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    codigo_iata       VARCHAR(3)   NOT NULL,
    nombre_aerolinea  VARCHAR(100) NOT NULL,
    CONSTRAINT pk_dim_aerolinea PRIMARY KEY (sk_aerolinea),
    CONSTRAINT uq_dim_aerolinea_codigo UNIQUE (codigo_iata)
);

COMMENT ON TABLE  dim_aerolinea IS 'Aerolíneas (SCD tipo 1)';
COMMENT ON COLUMN dim_aerolinea.codigo_iata IS 'Clave natural: airlines.IATA_CODE';

-- ---------------------------------------------------------------------
-- DIMENSIÓN AEROPUERTO (dimensión de rol: origen y destino)
-- Fuente: airports.csv (+ tabla de correspondencia estado -> región)
-- Jerarquía: Región > Estado > Ciudad > Aeropuerto
-- ---------------------------------------------------------------------
CREATE TABLE dim_aeropuerto (
    sk_aeropuerto      INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    codigo_iata        VARCHAR(3)   NOT NULL,
    nombre_aeropuerto  VARCHAR(150) NOT NULL,
    ciudad             VARCHAR(80)  NOT NULL,
    estado             CHAR(2)      NOT NULL,
    region             VARCHAR(15)  NOT NULL,
    pais               VARCHAR(30)  NOT NULL,
    latitud            NUMERIC(9,6) NULL,
    longitud           NUMERIC(9,6) NULL,
    CONSTRAINT pk_dim_aeropuerto PRIMARY KEY (sk_aeropuerto),
    CONSTRAINT uq_dim_aeropuerto_codigo UNIQUE (codigo_iata),
    CONSTRAINT ck_dim_aeropuerto_region CHECK (region IN
        ('Noreste', 'Medio Oeste', 'Sur', 'Oeste', 'Territorios', 'Desconocida')),
    CONSTRAINT ck_dim_aeropuerto_latitud CHECK (latitud BETWEEN -90 AND 90),
    CONSTRAINT ck_dim_aeropuerto_longitud CHECK (longitud BETWEEN -180 AND 180)
);

COMMENT ON TABLE  dim_aeropuerto IS 'Aeropuertos; la tabla de hechos la usa dos veces (origen y destino)';
COMMENT ON COLUMN dim_aeropuerto.codigo_iata IS 'Clave natural: airports.IATA_CODE';
COMMENT ON COLUMN dim_aeropuerto.region      IS 'Región censal de EE. UU. derivada del estado en el ETL';

-- ---------------------------------------------------------------------
-- DIMENSIÓN MOTIVO DE CANCELACIÓN
-- Fuente: flights.CANCELLATION_REASON (A, B, C, D) + "No cancelado"
-- ---------------------------------------------------------------------
CREATE TABLE dim_motivo_cancelacion (
    sk_motivo_cancelacion  SMALLINT     NOT NULL,
    codigo_motivo          CHAR(1)      NOT NULL,
    descripcion            VARCHAR(40)  NOT NULL,
    CONSTRAINT pk_dim_motivo_cancelacion PRIMARY KEY (sk_motivo_cancelacion),
    CONSTRAINT uq_dim_motivo_cancelacion_codigo UNIQUE (codigo_motivo),
    CONSTRAINT ck_dim_motivo_cancelacion_codigo CHECK (codigo_motivo IN ('N', 'A', 'B', 'C', 'D'))
);

COMMENT ON TABLE  dim_motivo_cancelacion IS 'Motivo de cancelación; N = vuelo no cancelado';

-- ---------------------------------------------------------------------
-- TABLA DE HECHOS: VUELO
-- Fuente: flights.csv
-- Granularidad: un registro por cada vuelo programado de una aerolínea
-- (fecha, aerolínea, número de vuelo, aeropuerto de origen y hora
-- programada de salida).
-- ---------------------------------------------------------------------
CREATE TABLE fact_vuelo (
    sk_vuelo                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    -- Claves foráneas hacia las dimensiones
    sk_fecha                    INTEGER      NOT NULL,
    sk_hora_salida              SMALLINT     NOT NULL,
    sk_aerolinea                INTEGER      NOT NULL,
    sk_aeropuerto_origen        INTEGER      NOT NULL,
    sk_aeropuerto_destino       INTEGER      NOT NULL,
    sk_motivo_cancelacion       SMALLINT     NOT NULL,
    -- Dimensiones degeneradas
    numero_vuelo                INTEGER      NOT NULL,
    matricula_avion             VARCHAR(10)  NULL,
    salida_programada           TIME         NOT NULL,
    -- Métricas en minutos (los retrasos negativos indican adelanto)
    retraso_salida_min          SMALLINT     NULL,
    retraso_llegada_min         SMALLINT     NULL,
    taxi_salida_min             SMALLINT     NULL,
    taxi_llegada_min            SMALLINT     NULL,
    tiempo_programado_min       SMALLINT     NULL,
    tiempo_real_min             SMALLINT     NULL,
    tiempo_aire_min             SMALLINT     NULL,
    distancia_millas            SMALLINT     NOT NULL,
    -- Minutos de retraso por causa (solo vuelos con 15 minutos o más de retraso)
    retraso_aerolinea_min       SMALLINT     NOT NULL DEFAULT 0,
    retraso_clima_min           SMALLINT     NOT NULL DEFAULT 0,
    retraso_sistema_aereo_min   SMALLINT     NOT NULL DEFAULT 0,
    retraso_seguridad_min       SMALLINT     NOT NULL DEFAULT 0,
    retraso_avion_tardio_min    SMALLINT     NOT NULL DEFAULT 0,
    -- Indicadores 0/1 (sumables en consultas y cubos OLAP)
    es_cancelado                SMALLINT     NOT NULL DEFAULT 0,
    es_desviado                 SMALLINT     NOT NULL DEFAULT 0,
    es_retrasado                SMALLINT     NOT NULL DEFAULT 0,
    es_puntual                  SMALLINT     NOT NULL DEFAULT 0,
    -- Auditoría del ETL
    fecha_carga                 TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_fact_vuelo PRIMARY KEY (sk_vuelo),
    CONSTRAINT uq_fact_vuelo_natural UNIQUE (sk_fecha, sk_aerolinea, numero_vuelo,
                                             sk_aeropuerto_origen, salida_programada),

    -- Integridad referencial (dim_aeropuerto se usa en dos roles)
    CONSTRAINT fk_fact_vuelo_fecha     FOREIGN KEY (sk_fecha)              REFERENCES dim_fecha (sk_fecha),
    CONSTRAINT fk_fact_vuelo_hora      FOREIGN KEY (sk_hora_salida)        REFERENCES dim_hora (sk_hora),
    CONSTRAINT fk_fact_vuelo_aerolinea FOREIGN KEY (sk_aerolinea)          REFERENCES dim_aerolinea (sk_aerolinea),
    CONSTRAINT fk_fact_vuelo_origen    FOREIGN KEY (sk_aeropuerto_origen)  REFERENCES dim_aeropuerto (sk_aeropuerto),
    CONSTRAINT fk_fact_vuelo_destino   FOREIGN KEY (sk_aeropuerto_destino) REFERENCES dim_aeropuerto (sk_aeropuerto),
    CONSTRAINT fk_fact_vuelo_motivo    FOREIGN KEY (sk_motivo_cancelacion) REFERENCES dim_motivo_cancelacion (sk_motivo_cancelacion),

    -- Reglas de dominio
    CONSTRAINT ck_fact_vuelo_numero CHECK (numero_vuelo > 0),
    CONSTRAINT ck_fact_vuelo_distancia CHECK (distancia_millas > 0),
    CONSTRAINT ck_fact_vuelo_taxi CHECK (taxi_salida_min >= 0 AND taxi_llegada_min >= 0),
    CONSTRAINT ck_fact_vuelo_tiempos CHECK (tiempo_programado_min > 0 AND tiempo_real_min > 0 AND tiempo_aire_min > 0),
    CONSTRAINT ck_fact_vuelo_causas CHECK (
        retraso_aerolinea_min >= 0 AND retraso_clima_min >= 0 AND retraso_sistema_aereo_min >= 0 AND
        retraso_seguridad_min >= 0 AND retraso_avion_tardio_min >= 0),
    CONSTRAINT ck_fact_vuelo_ruta CHECK (sk_aeropuerto_origen <> sk_aeropuerto_destino OR sk_aeropuerto_origen = -1),

    -- Indicadores binarios y coherencia con las métricas de origen
    CONSTRAINT ck_fact_vuelo_indicadores CHECK (
        es_cancelado IN (0, 1) AND es_desviado IN (0, 1) AND es_retrasado IN (0, 1) AND es_puntual IN (0, 1)),
    CONSTRAINT ck_fact_vuelo_un_estado CHECK (es_cancelado + es_desviado + es_retrasado + es_puntual <= 1),
    CONSTRAINT ck_fact_vuelo_cancelado CHECK ((es_cancelado = 1) = (sk_motivo_cancelacion <> 0)),
    CONSTRAINT ck_fact_vuelo_cancelado_sin_llegada CHECK (es_cancelado = 0 OR retraso_llegada_min IS NULL),
    CONSTRAINT ck_fact_vuelo_retrasado CHECK ((es_retrasado = 1) = (COALESCE(retraso_llegada_min, -1) >= 15)),
    CONSTRAINT ck_fact_vuelo_puntual CHECK ((es_puntual = 1) = (COALESCE(retraso_llegada_min, 15) < 15))
);

COMMENT ON TABLE  fact_vuelo IS 'Hechos: un vuelo programado de una aerolínea';
COMMENT ON COLUMN fact_vuelo.numero_vuelo          IS 'Dimensión degenerada: flights.FLIGHT_NUMBER';
COMMENT ON COLUMN fact_vuelo.matricula_avion       IS 'Dimensión degenerada: flights.TAIL_NUMBER';
COMMENT ON COLUMN fact_vuelo.salida_programada     IS 'Dimensión degenerada: flights.SCHEDULED_DEPARTURE (hhmm -> TIME)';
COMMENT ON COLUMN fact_vuelo.retraso_salida_min    IS 'flights.DEPARTURE_DELAY; negativo = salió antes. Aditiva';
COMMENT ON COLUMN fact_vuelo.retraso_llegada_min   IS 'flights.ARRIVAL_DELAY; nulo si fue cancelado o desviado. Aditiva';
COMMENT ON COLUMN fact_vuelo.taxi_salida_min       IS 'flights.TAXI_OUT: rodaje desde la puerta hasta el despegue. Aditiva';
COMMENT ON COLUMN fact_vuelo.taxi_llegada_min      IS 'flights.TAXI_IN: rodaje desde el aterrizaje hasta la puerta. Aditiva';
COMMENT ON COLUMN fact_vuelo.tiempo_programado_min IS 'flights.SCHEDULED_TIME. Aditiva';
COMMENT ON COLUMN fact_vuelo.tiempo_real_min       IS 'flights.ELAPSED_TIME. Aditiva';
COMMENT ON COLUMN fact_vuelo.tiempo_aire_min       IS 'flights.AIR_TIME. Aditiva';
COMMENT ON COLUMN fact_vuelo.distancia_millas      IS 'flights.DISTANCE. Aditiva';
COMMENT ON COLUMN fact_vuelo.es_retrasado          IS '1 si llegó con 15 minutos o más de retraso';
COMMENT ON COLUMN fact_vuelo.es_puntual            IS '1 si llegó con menos de 15 minutos de retraso';
