-- =====================================================================
-- Proyecto Base de Datos 3 - Data Warehouse de Fórmula 1
-- DataMart seleccionado: Rendimiento en Carrera
-- Script 01: esquema, tablas de dimensiones y tabla de hechos
-- DBMS: PostgreSQL 16
--
-- Ejecución:
--   createdb -U postgres -E UTF8 -T template0 dw_formula1
--   psql -U postgres -d dw_formula1 -f 01_crear_esquema_y_tablas.sql
--
-- ATENCIÓN: el script elimina y vuelve a crear el esquema dw_f1.
-- =====================================================================

DROP SCHEMA IF EXISTS dw_f1 CASCADE;
CREATE SCHEMA dw_f1;
COMMENT ON SCHEMA dw_f1 IS 'DataMart Rendimiento en Carrera - Campeonato Mundial de Fórmula 1 (1950 en adelante)';

SET search_path TO dw_f1;

-- ---------------------------------------------------------------------
-- DIMENSIÓN TIEMPO
-- Clave inteligente AAAAMMDD; se genera completa antes del ETL.
-- Jerarquía: Década > Año > Semestre > Trimestre > Mes > Fecha
-- ---------------------------------------------------------------------
CREATE TABLE dim_tiempo (
    sk_tiempo        INTEGER      NOT NULL,
    fecha            DATE         NOT NULL,
    dia              SMALLINT     NOT NULL,
    dia_semana       SMALLINT     NOT NULL,
    nombre_dia       VARCHAR(10)  NOT NULL,
    mes              SMALLINT     NOT NULL,
    nombre_mes       VARCHAR(10)  NOT NULL,
    trimestre        SMALLINT     NOT NULL,
    semestre         SMALLINT     NOT NULL,
    anio             SMALLINT     NOT NULL,
    decada           SMALLINT     NOT NULL,
    nombre_decada    VARCHAR(15)  NOT NULL,
    CONSTRAINT pk_dim_tiempo PRIMARY KEY (sk_tiempo),
    CONSTRAINT uq_dim_tiempo_fecha UNIQUE (fecha),
    CONSTRAINT ck_dim_tiempo_sk CHECK (sk_tiempo = EXTRACT(YEAR FROM fecha) * 10000
                                                 + EXTRACT(MONTH FROM fecha) * 100
                                                 + EXTRACT(DAY FROM fecha)),
    CONSTRAINT ck_dim_tiempo_dia CHECK (dia BETWEEN 1 AND 31),
    CONSTRAINT ck_dim_tiempo_dia_semana CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT ck_dim_tiempo_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_tiempo_trimestre CHECK (trimestre BETWEEN 1 AND 4),
    CONSTRAINT ck_dim_tiempo_semestre CHECK (semestre IN (1, 2)),
    CONSTRAINT ck_dim_tiempo_decada CHECK (decada = anio - anio % 10)
);

COMMENT ON TABLE  dim_tiempo IS 'Dimensión calendario: un registro por día';
COMMENT ON COLUMN dim_tiempo.sk_tiempo  IS 'Clave sustituta inteligente con formato AAAAMMDD';
COMMENT ON COLUMN dim_tiempo.dia_semana IS 'Día de la semana ISO: 1 = lunes ... 7 = domingo';
COMMENT ON COLUMN dim_tiempo.decada     IS 'Primer año de la década (1950, 1960, ...)';

-- ---------------------------------------------------------------------
-- DIMENSIÓN CARRERA (Gran Premio)
-- Fuente: races.csv, sprint_results.csv
-- Jerarquía: Temporada > Ronda (Gran Premio)
-- ---------------------------------------------------------------------
CREATE TABLE dim_carrera (
    sk_carrera              INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_carrera_origen       INTEGER      NOT NULL,
    temporada               SMALLINT     NOT NULL,
    ronda                   SMALLINT     NOT NULL,
    total_rondas_temporada  SMALLINT     NOT NULL,
    nombre_gran_premio      VARCHAR(100) NOT NULL,
    hora_inicio_utc         TIME         NULL,
    tiene_sprint            BOOLEAN      NOT NULL DEFAULT FALSE,
    sistema_puntos          VARCHAR(60)  NOT NULL,
    url_referencia          VARCHAR(255) NULL,
    CONSTRAINT pk_dim_carrera PRIMARY KEY (sk_carrera),
    CONSTRAINT uq_dim_carrera_origen UNIQUE (id_carrera_origen),
    CONSTRAINT uq_dim_carrera_temporada_ronda UNIQUE (temporada, ronda),
    CONSTRAINT ck_dim_carrera_temporada CHECK (temporada >= 1950),
    CONSTRAINT ck_dim_carrera_ronda CHECK (ronda BETWEEN 1 AND total_rondas_temporada)
);

COMMENT ON TABLE  dim_carrera IS 'Dimensión Gran Premio: un registro por carrera del campeonato';
COMMENT ON COLUMN dim_carrera.id_carrera_origen      IS 'Clave natural: races.raceId';
COMMENT ON COLUMN dim_carrera.total_rondas_temporada IS 'Cantidad de carreras de la temporada (derivado en el ETL)';
COMMENT ON COLUMN dim_carrera.tiene_sprint           IS 'Verdadero si el fin de semana incluyó carrera sprint';
COMMENT ON COLUMN dim_carrera.sistema_puntos         IS 'Sistema de puntuación vigente en la temporada (derivado en el ETL)';

-- ---------------------------------------------------------------------
-- DIMENSIÓN CIRCUITO
-- Fuente: circuits.csv (+ tabla de correspondencia país -> continente)
-- Jerarquía: Continente > País > Localidad > Circuito
-- ---------------------------------------------------------------------
CREATE TABLE dim_circuito (
    sk_circuito         INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_circuito_origen  INTEGER      NOT NULL,
    referencia          VARCHAR(50)  NOT NULL,
    nombre_circuito     VARCHAR(100) NOT NULL,
    localidad           VARCHAR(100) NOT NULL,
    pais                VARCHAR(60)  NOT NULL,
    continente          VARCHAR(20)  NOT NULL,
    latitud             NUMERIC(9,6) NULL,
    longitud            NUMERIC(9,6) NULL,
    altitud_m           INTEGER      NULL,
    CONSTRAINT pk_dim_circuito PRIMARY KEY (sk_circuito),
    CONSTRAINT uq_dim_circuito_origen UNIQUE (id_circuito_origen),
    CONSTRAINT ck_dim_circuito_continente CHECK (continente IN
        ('África', 'América del Norte', 'América del Sur', 'Asia', 'Europa', 'Oceanía', 'Desconocido')),
    CONSTRAINT ck_dim_circuito_latitud CHECK (latitud BETWEEN -90 AND 90),
    CONSTRAINT ck_dim_circuito_longitud CHECK (longitud BETWEEN -180 AND 180)
);

COMMENT ON TABLE  dim_circuito IS 'Dimensión circuito con su ubicación geográfica';
COMMENT ON COLUMN dim_circuito.id_circuito_origen IS 'Clave natural: circuits.circuitId';
COMMENT ON COLUMN dim_circuito.continente         IS 'Derivado en el ETL a partir del país';

-- ---------------------------------------------------------------------
-- DIMENSIÓN PILOTO
-- Fuente: drivers.csv
-- Jerarquía: Nacionalidad > Piloto
-- ---------------------------------------------------------------------
CREATE TABLE dim_piloto (
    sk_piloto           INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_piloto_origen    INTEGER      NOT NULL,
    referencia          VARCHAR(50)  NOT NULL,
    codigo              CHAR(3)      NULL,
    numero_permanente   SMALLINT     NULL,
    nombre              VARCHAR(60)  NOT NULL,
    apellido            VARCHAR(60)  NOT NULL,
    nombre_completo     VARCHAR(120) NOT NULL,
    fecha_nacimiento    DATE         NULL,
    nacionalidad        VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_dim_piloto PRIMARY KEY (sk_piloto),
    CONSTRAINT uq_dim_piloto_origen UNIQUE (id_piloto_origen),
    CONSTRAINT ck_dim_piloto_numero CHECK (numero_permanente BETWEEN 0 AND 99)
);

COMMENT ON TABLE  dim_piloto IS 'Dimensión piloto (SCD tipo 1)';
COMMENT ON COLUMN dim_piloto.id_piloto_origen  IS 'Clave natural: drivers.driverId';
COMMENT ON COLUMN dim_piloto.codigo            IS 'Código de tres letras (ej. VER, HAM); nulo en pilotos antiguos';
COMMENT ON COLUMN dim_piloto.numero_permanente IS 'Número permanente (desde 2014); nulo en pilotos antiguos';

-- ---------------------------------------------------------------------
-- DIMENSIÓN ESCUDERÍA (constructor)
-- Fuente: constructors.csv
-- Jerarquía: Nacionalidad > Escudería
-- ---------------------------------------------------------------------
CREATE TABLE dim_escuderia (
    sk_escuderia          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_escuderia_origen   INTEGER      NOT NULL,
    referencia            VARCHAR(50)  NOT NULL,
    nombre_escuderia      VARCHAR(100) NOT NULL,
    nacionalidad          VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_dim_escuderia PRIMARY KEY (sk_escuderia),
    CONSTRAINT uq_dim_escuderia_origen UNIQUE (id_escuderia_origen)
);

COMMENT ON TABLE  dim_escuderia IS 'Dimensión escudería o constructor (SCD tipo 1)';
COMMENT ON COLUMN dim_escuderia.id_escuderia_origen IS 'Clave natural: constructors.constructorId';

-- ---------------------------------------------------------------------
-- DIMENSIÓN ESTADO DE FINALIZACIÓN
-- Fuente: status.csv (+ regla de clasificación por categoría)
-- Jerarquía: Categoría > Estado
-- ---------------------------------------------------------------------
CREATE TABLE dim_estado (
    sk_estado           INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    id_estado_origen    INTEGER     NOT NULL,
    descripcion_estado  VARCHAR(60) NOT NULL,
    categoria_estado    VARCHAR(40) NOT NULL,
    CONSTRAINT pk_dim_estado PRIMARY KEY (sk_estado),
    CONSTRAINT uq_dim_estado_origen UNIQUE (id_estado_origen),
    CONSTRAINT ck_dim_estado_categoria CHECK (categoria_estado IN
        ('Finalizó', 'Finalizó con vueltas de retraso', 'Falla mecánica',
         'Accidente o colisión', 'Descalificación', 'No largó o no clasificó',
         'Otro', 'Desconocido'))
);

COMMENT ON TABLE  dim_estado IS 'Dimensión estado de finalización del piloto en la carrera';
COMMENT ON COLUMN dim_estado.id_estado_origen IS 'Clave natural: status.statusId';
COMMENT ON COLUMN dim_estado.categoria_estado IS 'Agrupación del estado original (derivada en el ETL)';

-- ---------------------------------------------------------------------
-- TABLA DE HECHOS: RESULTADO DE CARRERA
-- Fuente: results.csv (+ races, drivers, driver_standings)
-- Granularidad: un registro por cada resultado de un piloto con un auto
-- en un Gran Premio del campeonato (results.resultId).
-- ---------------------------------------------------------------------
CREATE TABLE fact_resultado_carrera (
    sk_resultado                 BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    -- Claves foráneas hacia las dimensiones
    sk_tiempo                    INTEGER      NOT NULL,
    sk_carrera                   INTEGER      NOT NULL,
    sk_circuito                  INTEGER      NOT NULL,
    sk_piloto                    INTEGER      NOT NULL,
    sk_escuderia                 INTEGER      NOT NULL,
    sk_estado                    INTEGER      NOT NULL,
    -- Dimensiones degeneradas
    id_resultado_origen          INTEGER      NOT NULL,
    numero_auto                  SMALLINT     NULL,
    codigo_posicion              VARCHAR(3)   NOT NULL,
    -- Métricas de posición y rendimiento
    posicion_salida              SMALLINT     NOT NULL,
    posicion_final               SMALLINT     NULL,
    orden_llegada                SMALLINT     NOT NULL,
    posiciones_ganadas           SMALLINT     NULL,
    puntos                       NUMERIC(5,2) NOT NULL DEFAULT 0,
    puntos_sistema_actual        NUMERIC(5,2) NOT NULL DEFAULT 0,
    vueltas_completadas          SMALLINT     NOT NULL DEFAULT 0,
    tiempo_carrera_ms            BIGINT       NULL,
    tiempo_vuelta_rapida_ms      INTEGER      NULL,
    velocidad_vuelta_rapida_kmh  NUMERIC(7,3) NULL,
    ranking_vuelta_rapida        SMALLINT     NULL,
    edad_piloto                  NUMERIC(4,1) NULL,
    -- Métricas del campeonato después de la carrera
    puntos_acumulados_temporada  NUMERIC(6,2) NULL,
    posicion_campeonato          SMALLINT     NULL,
    -- Indicadores 0/1 (sumables en consultas y cubos OLAP)
    es_victoria                  SMALLINT     NOT NULL DEFAULT 0,
    es_podio                     SMALLINT     NOT NULL DEFAULT 0,
    es_pole                      SMALLINT     NOT NULL DEFAULT 0,
    es_en_puntos                 SMALLINT     NOT NULL DEFAULT 0,
    es_vuelta_rapida             SMALLINT     NOT NULL DEFAULT 0,
    es_finalizado                SMALLINT     NOT NULL DEFAULT 0,
    es_abandono                  SMALLINT     NOT NULL DEFAULT 0,
    -- Auditoría del ETL
    fecha_carga                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_fact_resultado_carrera PRIMARY KEY (sk_resultado),
    CONSTRAINT uq_fact_resultado_origen UNIQUE (id_resultado_origen),

    -- Integridad referencial
    CONSTRAINT fk_fact_resultado_tiempo    FOREIGN KEY (sk_tiempo)    REFERENCES dim_tiempo (sk_tiempo),
    CONSTRAINT fk_fact_resultado_carrera   FOREIGN KEY (sk_carrera)   REFERENCES dim_carrera (sk_carrera),
    CONSTRAINT fk_fact_resultado_circuito  FOREIGN KEY (sk_circuito)  REFERENCES dim_circuito (sk_circuito),
    CONSTRAINT fk_fact_resultado_piloto    FOREIGN KEY (sk_piloto)    REFERENCES dim_piloto (sk_piloto),
    CONSTRAINT fk_fact_resultado_escuderia FOREIGN KEY (sk_escuderia) REFERENCES dim_escuderia (sk_escuderia),
    CONSTRAINT fk_fact_resultado_estado    FOREIGN KEY (sk_estado)    REFERENCES dim_estado (sk_estado),

    -- Reglas de dominio de las métricas
    CONSTRAINT ck_fact_codigo_posicion CHECK (codigo_posicion ~ '^([0-9]{1,2}|R|D|E|W|F|N)$'),
    CONSTRAINT ck_fact_posicion_salida CHECK (posicion_salida >= 0),
    CONSTRAINT ck_fact_posicion_final CHECK (posicion_final > 0),
    CONSTRAINT ck_fact_orden_llegada CHECK (orden_llegada > 0),
    CONSTRAINT ck_fact_puntos CHECK (puntos >= 0),
    CONSTRAINT ck_fact_puntos_actual CHECK (puntos_sistema_actual BETWEEN 0 AND 25),
    CONSTRAINT ck_fact_vueltas CHECK (vueltas_completadas >= 0),
    CONSTRAINT ck_fact_tiempo_carrera CHECK (tiempo_carrera_ms > 0),
    CONSTRAINT ck_fact_tiempo_vuelta CHECK (tiempo_vuelta_rapida_ms > 0),
    CONSTRAINT ck_fact_velocidad CHECK (velocidad_vuelta_rapida_kmh > 0),
    CONSTRAINT ck_fact_ranking_vuelta CHECK (ranking_vuelta_rapida > 0),
    CONSTRAINT ck_fact_edad CHECK (edad_piloto BETWEEN 14 AND 70),
    CONSTRAINT ck_fact_puntos_acumulados CHECK (puntos_acumulados_temporada >= 0),
    CONSTRAINT ck_fact_posicion_campeonato CHECK (posicion_campeonato > 0),

    -- Indicadores binarios y coherencia con las métricas de origen
    CONSTRAINT ck_fact_indicadores CHECK (
        es_victoria IN (0, 1) AND es_podio IN (0, 1) AND es_pole IN (0, 1) AND
        es_en_puntos IN (0, 1) AND es_vuelta_rapida IN (0, 1) AND
        es_finalizado IN (0, 1) AND es_abandono IN (0, 1)),
    CONSTRAINT ck_fact_victoria CHECK ((es_victoria = 1) = (COALESCE(posicion_final, 0) = 1)),
    CONSTRAINT ck_fact_podio CHECK ((es_podio = 1) = (COALESCE(posicion_final, 99) <= 3)),
    CONSTRAINT ck_fact_pole CHECK ((es_pole = 1) = (posicion_salida = 1)),
    CONSTRAINT ck_fact_en_puntos CHECK ((es_en_puntos = 1) = (puntos > 0)),
    CONSTRAINT ck_fact_vuelta_rapida CHECK ((es_vuelta_rapida = 1) = (COALESCE(ranking_vuelta_rapida, 0) = 1)),
    CONSTRAINT ck_fact_finalizado CHECK ((es_finalizado = 1) = (posicion_final IS NOT NULL)),
    CONSTRAINT ck_fact_abandono CHECK ((es_abandono = 1) = (codigo_posicion = 'R'))
);

COMMENT ON TABLE  fact_resultado_carrera IS 'Hechos: resultado de un piloto con un auto en un Gran Premio';
COMMENT ON COLUMN fact_resultado_carrera.id_resultado_origen         IS 'Dimensión degenerada: results.resultId';
COMMENT ON COLUMN fact_resultado_carrera.numero_auto                 IS 'Dimensión degenerada: número del auto en la carrera';
COMMENT ON COLUMN fact_resultado_carrera.codigo_posicion             IS 'Dimensión degenerada: posición oficial o código R/D/E/W/F/N';
COMMENT ON COLUMN fact_resultado_carrera.posicion_salida             IS 'Posición en la grilla de salida (0 = largó desde boxes o sin dato). No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.posicion_final              IS 'Posición final clasificada; nula si no fue clasificado. No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.orden_llegada               IS 'Orden final de todos los participantes, incluidos no clasificados. No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.posiciones_ganadas          IS 'posicion_salida - posicion_final para clasificados que largaron desde la grilla. Aditiva';
COMMENT ON COLUMN fact_resultado_carrera.puntos                      IS 'Puntos oficiales obtenidos en el Gran Premio. Aditiva';
COMMENT ON COLUMN fact_resultado_carrera.puntos_sistema_actual       IS 'Puntos recalculados con el sistema 25-18-15-12-10-8-6-4-2-1. Aditiva';
COMMENT ON COLUMN fact_resultado_carrera.vueltas_completadas         IS 'Vueltas completadas en la carrera. Aditiva';
COMMENT ON COLUMN fact_resultado_carrera.tiempo_carrera_ms           IS 'Tiempo total de carrera en milisegundos (solo en la vuelta del líder). No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.tiempo_vuelta_rapida_ms     IS 'Mejor vuelta del piloto en milisegundos (desde 2004). No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.velocidad_vuelta_rapida_kmh IS 'Velocidad media de la mejor vuelta en km/h (desde 2004). No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.ranking_vuelta_rapida       IS 'Ranking de la mejor vuelta dentro de la carrera (1 = más rápida). No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.edad_piloto                 IS 'Edad del piloto en años a la fecha de la carrera. No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.puntos_acumulados_temporada IS 'Puntos del piloto en el campeonato tras la carrera (incluye sprints). Semiaditiva';
COMMENT ON COLUMN fact_resultado_carrera.posicion_campeonato         IS 'Posición del piloto en el campeonato tras la carrera. No aditiva';
COMMENT ON COLUMN fact_resultado_carrera.es_pole                     IS '1 si largó desde la primera posición de la grilla';
COMMENT ON COLUMN fact_resultado_carrera.es_abandono                 IS '1 si se retiró sin ser clasificado (codigo_posicion = R)';
